version: '3.7'
services:
  gerocuidado-template-api-prod:
    image: gerocuidadodev/gerocuidado-template-api:latest
    container_name: gerocuidado-template-api-prod
    environment:
      - DB_HOST=gerocuidado-template-db
      - DB_USERNAME=postgres
      - DB_PASS=postgres
      - DB_DATABASE=gerocuidado-template-db
      - DB_PORT=500x
    ports:
      - '300x:300x'
    depends_on:
      - gerocuidado-template-db
    networks:
      - gerocuidado-template-net

  gerocuidado-template-db:
    build:
      context: ./.docker/postgres
      dockerfile: Dockerfile
    command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'
    container_name: gerocuidado-template-db
    volumes:
      - './.docker/postgres/config/postgresql.conf:/etc/postgresql/postgresql.conf'
    environment:
      - POSTGRES_DB=gerocuidado-template-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '500x:500x'
    networks:
      - gerocuidado-template-net

networks:
  gerocuidado-template-net:
    driver: bridge
